apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  type: NodePort
  selector:
    app: getting-started
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007