name: docker-ci-pipeline
on: push

jobs: 
  build-sysfoo:
     runs-on: ubuntu-latest
  
     steps:
        - name: Code checkout or code clone
          uses: actions/checkout@v5

        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.kvsatishkumar7 }}
            password: ${{ secrets.Pandu@123 }}
        
        - name: Docker Build
          run: docker build -t ${{ secrets.kvsatishkumar7 }}/sysfoo:v1
        
        - name: Docker push
          run: docker push ${{ secrets.kvsatishkumar7 }}/sysfoo:v1
